#!/bin/bash -eu
# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This requires https://github.com/Feneric/doxypypy which filters
# python doc strings so they're understood by doxygen.
#
# git clone https://github.com/Feneric/doxypypy
# cd doxypypy
# sudo python -m setup install
#
python -m doxypypy.doxypypy -a -c $1
